name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create .env.production
        run: |
          echo "Creating .env.production file..."
          cat > .env.production << 'EOF'
          REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID }}
          REACT_APP_FIREBASE_MEASUREMENT_ID=${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID }}
          EOF
          echo ".env.production file created successfully"
          echo "File contents (without sensitive data):"
          echo "REACT_APP_FIREBASE_API_KEY=[HIDDEN]"
          echo "REACT_APP_FIREBASE_AUTH_DOMAIN=[HIDDEN]"
          echo "REACT_APP_FIREBASE_PROJECT_ID=[HIDDEN]"
          echo "REACT_APP_FIREBASE_STORAGE_BUCKET=[HIDDEN]"
          echo "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=[HIDDEN]"
          echo "REACT_APP_FIREBASE_APP_ID=[HIDDEN]"
          echo "REACT_APP_FIREBASE_MEASUREMENT_ID=[HIDDEN]"

      - name: Verify .env.production
        run: |
          echo "Verifying .env.production file..."
          if [ -f .env.production ]; then
            echo "✅ .env.production file exists"
            echo "File size: $(wc -c < .env.production) bytes"
            echo "Number of lines: $(wc -l < .env.production)"
            echo "Checking if all required variables are set..."
            if grep -q "REACT_APP_FIREBASE_API_KEY=" .env.production && \
               grep -q "REACT_APP_FIREBASE_PROJECT_ID=" .env.production && \
               grep -q "REACT_APP_FIREBASE_AUTH_DOMAIN=" .env.production; then
              echo "✅ All required Firebase variables are present"
            else
              echo "❌ Some required Firebase variables are missing"
              exit 1
            fi
          else
            echo "❌ .env.production file not found"
            exit 1
          fi

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:github
        env:
          CI: false
          GENERATE_SOURCEMAP: false
          DISABLE_ESLINT_PLUGIN: true

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_REMEN_ABS }}'
          channelId: live
          projectId: remen-abs
          entryPoint: ./
